# Generated by Django 4.2.4 on 2023-08-27 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('openingday', models.DateField()),
                ('trailer', models.CharField(max_length=500)),
                ('stillshot1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stillshot2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stillshot3', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movieinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
